### ISSUE TITLE
Support for rollup

### ISSUE THREAD

**Issue by lucat1** [deamme/ts-transform-inferno#1]
Support for rollup would be amazing! 😍 

You can find some docs/examples here:
https://github.com/ezolenko/rollup-plugin-typescript2
https://github.com/rollup/rollup/wiki/Plugins#creating-plugins

**Comment by deamme** [comment]
This may already be possible if you're using [FuseBox](https://github.com/fuse-box/fuse-box). Check out http://fuse-box.org/page/rollup.

**Comment by lucat1** [comment]
I currently am not. Would it be hard to port it to a proper rollup plugin?

**Comment by deamme** [comment]
I think it would take a long time. Perhaps https://github.com/ezolenko/rollup-plugin-typescript2 should implement custom transformers.

**Comment by deamme** [comment]
Should be fixed by https://github.com/deamme/ts-transform-inferno/pull/6?

EDIT:
I guess not.. it's not about any rollup plugins

**Comment by hronro** [comment]
@deamme I'm using `rollup-plugin-typescript2`, and it works with `ts-transform-inferno` perfectly.

**Comment by hronro** [comment]
I send a [PR](https://github.com/deamme/ts-transform-inferno/pull/7) for adding example of Rollup

**Comment by deamme** [comment]
@foisonocean That's so great, thank you so much
