### ISSUE TITLE
TSX compilation does not work

### ISSUE THREAD

**Issue by b-gyula** [deamme/ts-transform-inferno#15]
This transform library seems to be a great solution. Much faster and stricter than the babel-plugin-inferno.
But it is not able to properly compile a simple login dialog as this:

`<div id="login" role="dialog">
					<h1>Login<span class="float-right">or&nbsp;<button>Sign Up</button></span></h1>
					<form id="loginForm" onSubmit={ this._onSubmit }>
						<label>User
							<input type="text" name="userName" required/></label>
						<label>password
							<input type="password" name="password" required/></label>
							<span>{state.error}</span>
						<button type="submit" disabled={state.loading}>Login</button>
					</form>
				</div>`

In he browser it gives the error:
`Uncaught (in promise) TypeError: Cannot create property 'flags' on string 'Login'`

On  other routes: `Uncaught TypeError: Cannot read property '$EV' of null`

I'm using ts-transform-inferno@4.0.1, inferno@7.0.4,  typescript@3.2.2, rollup@1.0.1

Is it some version problem?

**Comment by deamme** [comment]
There was a text sibling issue which has been fixed now. Just update to the newest version 4.0.2. It should fix your issue

**Comment by b-gyula** [comment]
It works perfectly! Thanks!
