### ISSUE TITLE
Question about ts-transform-classcat in examples

### ISSUE THREAD

**Issue by 3cp** [deamme/ts-transform-inferno#24]
I noticed ts-transform-classcat is in examples for fuse-box and also webpack, but not in example for rollup.

Is it overlooked for rollup example? Or ts-transform-classcat is simply not needed in rollup setup?

**Comment by Havunen** [comment]
It is not needed for any build setups. That is just another plugin that converts class object to call classcat function. You can do that manually or just use string as html node class name. See example here: https://github.com/deamme/ts-transform-classcat

I also recommend using https://github.com/infernojs/ts-plugin-inferno over this plugin, it supports latest version of inferno and typescript
