### ISSUE TITLE
TypeScript should be a peerDependency, not a dependency.

### ISSUE THREAD

**Issue by SalvatorePreviti** [deamme/ts-transform-inferno#8]
Great package :) however, using this package it happened to me to receive a "cannot read property length of undefined" while compiling and using fuse-box and typescript 3.0.
It turns out that ts-transform-inferno has a direct dependency to typescript 2.7.1, so instead of using typescript 3.0.0 in the root node_modules it uses typescript 2.7.1 in node_modules/ts-transform-inferno/node_modules.

To solve versioning problems, typescript should be a peerDependency and not a dependency.

Final code in package.json

```
"peerDependencies": {
    "typescript": ">=2.7.1"
  },
  "devDependencies": {
    "typescript": "^2.7.1",
    "@types/node": "^8.0.53",
    "fs-extra": "^4.0.2",
    "glob": "^7.1.2",
    "rimraf": "^2.6.2",
    "ts-node": "^3.3.0"
  }
```

**Comment by deamme** [comment]
Good catch! Thank you

**Comment by SalvatorePreviti** [comment]
Thanks :) it worked, now it compiles also with TypeScript 3.0.3

**Comment by deamme** [comment]
@SalvatorePreviti Awesome
